#!/usr/bin/env python3

# -------------------------
# INTRODUCTION -> some utils informations about the Python script
# -------------------------


"""
- MODALITÀ:
    Il file contiene la funzione query_gemini() che crea il client per mandare il prompt a LLM gemini 
    (è possibile scegliere il modello). Tutte le funzionalità per il supporto all'approccio RAG (Retrieval-Augmented Generation)
    sono contenute all'interno del file core_rag.py in quanto in comune con lo script evaluate_ollama_rag.py. 

- PRE-REQUISITI (comandi da eseguire da riga di comando):

    export GOOGLE_API_KEY=CHIAVE API    -> comando per esportare in locale la chiave per eseguire API Gemini (da rifare ogni volta che si chiude il terminale)
    source .env/bin/activate            -> comando per attivare enviroment virtuale
    pip install chromedb                
    pip install sentence-transformers    

- COMANDO PER ESECUZIONE (ATTENZIONE -> è necessario eseguire la prima riga di pre-requisiti ogni volta che si chiude il terminale):
    
    - Prova su pochi file del dataset (contenuti nella cartella ./data)
    
        python3 prompting/evaluate_gemini_rag.py --sessions output/cowrie_TEST.jsonl --index-file output/cowrie_TRAIN.jsonl --k 5 --rag-k 3 --context-len 5 --n 10

    - Intero dataset (contenuto su dispositivo di archiviazione esterna)  

        python3 prompting/evaluate_gemini_rag.py --sessions /media/matteo/T9/outputMerge/cowrie_TEST.jsonl --index-file /media/matteo/T9/outputMerge/cowrie_TRAIN.jsonl --persist-dir /media/matteo/T9/chroma_storage  --k 5 --rag-k 3 --context-len 5 --n 10

    dove le varie flag sono:
    - sessions = per specificare file jsonl contenente le sessioni per eseguire prediction
    - persist-dir = per specificare cartella contenente DB vettoriale
    - index-file = per specificare file jsonl per indicizzazione del DB vettoriale (se diverso da sessions)
    - output = per specificare nome del file dove verranno generati i risultati della prediction
    - model = per specificare nome modello Gemini
    - k = candidati proposti come next command dell'attaccante
    - rag-k = esempi storici da recuperare nel DB vettoriale
    - context-len = numero di comandi che rappresentano il contesto di attacco
    - n = numero di prediction da eseguire (0 = una prediction per ogni sessione del file di input)
"""

# -------------------------
# IMPORT SECTION -> imports necessary for the Python script
# -------------------------

from __future__ import annotations
import argparse
import os
import sys
import core_rag
from google.genai.types import HarmCategory, HarmBlockThreshold
from google.genai import Client

# =============================================================================
# GEMINI CALLER SECTION -> The function sends a prompt to a model managed by Ollama via an HTTP POST request and returns the response generated by the model.
# =============================================================================

api_key = os.getenv("GOOGLE_API_KEY")
if not api_key:
    sys.exit("ERRORE CRITICO: La variabile d'ambiente GOOGLE_API_KEY non è impostata.")

client_gemini = Client(api_key=api_key)

def query_gemini(prompt: str, model_name: str, temp: float = 0.0) -> str:

    try:
        #Visto che stiamo simulando degli attacchi, è necessario disattivare i blocchi di sicurezza
        safety_config = [
            {"category": HarmCategory.HARM_CATEGORY_HATE_SPEECH, "threshold": HarmBlockThreshold.BLOCK_NONE},
            {"category": HarmCategory.HARM_CATEGORY_HARASSMENT, "threshold": HarmBlockThreshold.BLOCK_NONE},
            {"category": HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, "threshold": HarmBlockThreshold.BLOCK_NONE},
            {"category": HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, "threshold": HarmBlockThreshold.BLOCK_NONE},
        ]

        response = client_gemini.models.generate_content(
            model=model_name,
            contents=prompt,
            config={
                "temperature": temp,
                "top_p": 0.1,
                "max_output_tokens": 1024,
                "safety_settings": safety_config # APPLICHIAMO I FILTRI PERMISSIVI
            }
        )
        
        # Controllo difensivo: se il modello restituisce None o non ha testo
        if not response or not response.text: return "" 
        else: return response.text

    except Exception as exc:
        err_str = str(exc)
        # Gestione dell'errore in caso di error 404
        if "404" in err_str: 
            print(f"\n[ERRORE FATALE] Modello '{model_name}' non trovato.")
            sys.exit(1)
        # Restituzione di una stringa vuota per non rompere il loop
        return ""

# =============================================================================
# SECTION MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="Evaluate Gemini with RAG Vector Search")
    parser.add_argument("--sessions", required=True, help="File jsonl contenente le sessioni per eseguire prediction")
    parser.add_argument("--persist-dir", default="./chroma_storage", help="Cartella contenente DB vettoriale")
    parser.add_argument("--index-file", help="File jsonl per indicizzazione del DB vettoriale (se diverso da sessions)")
    parser.add_argument("--output", default=None, help="Nome del file dove verranno generati i risultati della prediction")
    parser.add_argument("--model", default="gemini-flash-latest", help="Nome modello (es. gemini-1.5-pro-latest, gemini-pro)")  # modello spesso più stabile
    parser.add_argument("--k", type=int, default=5, help="Candidati proposti come next command dell'attaccante")
    parser.add_argument("--rag-k", type=int, default=3, help="Esempi storici da recuperare nel DB vettoriale")
    parser.add_argument("--context-len", type=int, default=5, help="Numero di comandi che rappresentano il contesto di attacco")
    parser.add_argument("--n", type=int, default=0, help="Numero di prediction da eseguire (0 = una prediction per ogni sessione del file di input)")

    args = parser.parse_args()

    if args.output is None: args.output = f"output/rag/gemini_rag_results_n{args.n}_ctx{args.context_len}_k{args.k}.jsonl"
    # Modifico il nome della cartella di contenimento dei vettori -> db fortemente influenzato da context_len
    args.persist_dir = f"{args.persist_dir}_ctx{args.context_len}"

    core_rag.prediction_evaluation(args, "gemini", query_model=query_gemini)

if __name__ == "__main__":
    main()